version: '3.8'

services:

  db:
    image: postgres:15
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: task-backend
    restart: always
    ports:
      - "3500:3500"
    environment:
      DB_HOST: db
      DB_NAME: tasksdb
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build:
      context: ./task-frontend
      args:
        REACT_APP_BACKEND_URL: http://65.0.21.23:3500
    container_name: task-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: