apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: notes-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
      - name: ecr-registry-secret

      containers:
      - name: frontend
        image: 566849586744.dkr.ecr.ap-south-1.amazonaws.com/eks-notes-app-frontend:latest

        ports:
        - containerPort: 3000

        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_BACKEND_URL